USE C4707F24S002U1;

DROP DATABASE C4707F24S002U1;
CREATE DATABASE C4707F24S002U1;
USE C4707F24S002U1;

CREATE TABLE PATIENT (
  PID INT NOT NULL,
  DOB DATE DEFAULT NULL,
  FNAME VARCHAR(100) NOT NULL,
  MINITIAL CHAR(2) DEFAULT NULL,
  LNAME VARCHAR(100) NOT NULL,
  ADDR VARCHAR(100) NOT NULL,
  EMERCONTACT VARCHAR(100) NOT NULL,
  INSURANCEINFO VARCHAR(100) NOT NULL,
  PRIMARY KEY (PID)
);

CREATE TABLE PARENT_GUARDIAN (
  GUARDIANID INT NOT NULL,
  PID INT DEFAULT NULL,
  RELATIONTOPATIENT VARCHAR(50) DEFAULT NULL,
  PHONENO VARCHAR(20) DEFAULT NULL,
  EMAIL VARCHAR(255) DEFAULT NULL,
  FNAME VARCHAR(100) NOT NULL,
  MINITIAL CHAR(2) DEFAULT NULL,
  LNAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (GUARDIANID),
  KEY PID (PID),
  FOREIGN KEY (PID) REFERENCES PATIENT(PID)
);


CREATE TABLE PATIENT_ADDRESS (
  PID INT NOT NULL,
  ADDRESS VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (PID),
  FOREIGN KEY (PID) REFERENCES PATIENT(PID)
);

CREATE TABLE DEPARTMENT (
  DEPARTMENTID INT NOT NULL,
  DEPARTMENTNAME VARCHAR(100) NOT NULL,
  PRIMARY KEY (DEPARTMENTID)
);

CREATE TABLE EMPLOYEE (
  EMPLOYEEID INT NOT NULL,
  SSN CHAR(9) DEFAULT NULL,
  DEPARTMENTID INT DEFAULT NULL,
  FNAME VARCHAR(100) NOT NULL,
  MINITIAL CHAR(2) DEFAULT NULL,
  LNAME VARCHAR(100) NOT NULL,
  HOURLY INT DEFAULT NULL,
  SALARIED INT DEFAULT NULL,
  PRIMARY KEY (EMPLOYEEID),
  KEY DEPARTMENTID (DEPARTMENTID),
  FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID)
);
CREATE TABLE ADDITIONAL_STAFF (
  EMPLOYEEID INT NOT NULL,
  PRIMARY KEY (EMPLOYEEID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE TREATMENT (
  TREATMENTID INT NOT NULL,
  TREATMENTCOST DECIMAL(10,2) DEFAULT NULL,
  TREATMENTNAME VARCHAR(255) DEFAULT NULL,
  ICD_10_PCSCODE VARCHAR(20) DEFAULT NULL,
  VISITID INT DEFAULT NULL,
  PRIMARY KEY (TREATMENTID)
);

CREATE TABLE NURSE (
  EMPLOYEEID INT NOT NULL,
  NURSINGLICENSE VARCHAR(50) DEFAULT NULL,
  PRIMARY KEY (EMPLOYEEID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE VISIT (
  VISITID INT NOT NULL,
  PID INT DEFAULT NULL,
  VDATE DATE DEFAULT NULL,
  VTIME TIME DEFAULT NULL,
  INTAKECLERKEMPLOYEEID INT DEFAULT NULL,
  NURSEEMPLOYEEID INT DEFAULT NULL,
  SERVICEPROVIDERID INT DEFAULT NULL,
  COPAYMETHOD VARCHAR(50) DEFAULT NULL,
  ONLINEFORM INT DEFAULT NULL,
  NOTES TEXT,
  PRIMARY KEY (VISITID),
  KEY PID (PID),
  KEY INTAKECLERKEMPLOYEEID (INTAKECLERKEMPLOYEEID),
  KEY NURSEEMPLOYEEID (NURSEEMPLOYEEID),
  KEY SERVICEPROVIDERID (SERVICEPROVIDERID),
  FOREIGN KEY (PID) REFERENCES PATIENT(PID),
  FOREIGN KEY (INTAKECLERKEMPLOYEEID) REFERENCES ADDITIONAL_STAFF(EMPLOYEEID),
  FOREIGN KEY (NURSEEMPLOYEEID) REFERENCES NURSE(EMPLOYEEID),
  FOREIGN KEY (SERVICEPROVIDERID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE APPROVE_MINOR (
  GUARDIANID INT NOT NULL,
  TREATMENTID INT NOT NULL,
  VISITID INT NOT NULL,
  PID INT DEFAULT NULL,
  DIGITALSIGNATURE INT DEFAULT NULL,
  HARDCOPYSIG INT DEFAULT NULL,
  PRIMARY KEY (GUARDIANID, TREATMENTID, VISITID),
  KEY TREATMENTID (TREATMENTID),
  KEY VISITID (VISITID),
  KEY PID (PID),
  FOREIGN KEY (GUARDIANID) REFERENCES PARENT_GUARDIAN(GUARDIANID),
  FOREIGN KEY (TREATMENTID) REFERENCES TREATMENT(TREATMENTID),
  FOREIGN KEY (VISITID) REFERENCES VISIT(VISITID),
  FOREIGN KEY (PID) REFERENCES PATIENT(PID)
);

CREATE TABLE BILLING_CLERK (
  EMPLOYEEID INT NOT NULL,
  SSN CHAR(9) NOT NULL,
  DEPARTMENTID INT DEFAULT NULL,
  FNAME VARCHAR(100) NOT NULL,
  MINITIAL CHAR(2) DEFAULT NULL,
  LNAME VARCHAR(100) NOT NULL,
  HOURLY INT DEFAULT NULL,
  SALARIED INT DEFAULT NULL,
  PRIMARY KEY (EMPLOYEEID),
  KEY DEPARTMENTID (DEPARTMENTID),
  FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE DEGREES (
  EMPLOYEEID INT DEFAULT NULL,
  DEGREE VARCHAR(100) DEFAULT NULL,
  DLOCATION VARCHAR(255) DEFAULT NULL,
  UNIVERSITY VARCHAR(255) DEFAULT NULL,
  DATEOFDEGREECONFERRAL DATE DEFAULT NULL,
  KEY EMPLOYEEID (EMPLOYEEID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);


CREATE TABLE DIAGNOSIS (
  DIAGNOSISID INT NOT NULL,
  DIAGNOSISNAME VARCHAR(255) DEFAULT NULL,
  ICD_10_CM_CODE VARCHAR(20) DEFAULT NULL,
  PRIMARY KEY (DIAGNOSISID)
);

CREATE TABLE DOCTOR (
  EMPLOYEEID INT NOT NULL,
  PRIMARY KEY (EMPLOYEEID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE (EMPLOYEEID)
);



CREATE TABLE HAS_GUARDIAN (
  PID INT NOT NULL,
  GUARDIANID INT NOT NULL,
  CUSTODYSTARTDATE DATE DEFAULT NULL,
  CUSTODYENDDATE DATE DEFAULT NULL,
  PRIMARY KEY (PID, GUARDIANID),
  KEY GUARDIANID (GUARDIANID),
  FOREIGN KEY (PID) REFERENCES PATIENT(PID),
  FOREIGN KEY (GUARDIANID) REFERENCES PARENT_GUARDIAN(GUARDIANID)
);
CREATE TABLE INSURANCE_PROVIDER (
  INSURANCEID INT NOT NULL,
  INSURANCESTATE VARCHAR(50) DEFAULT NULL,
  COMPANYNAME VARCHAR(100) DEFAULT NULL,
  POLICYNO VARCHAR(50) DEFAULT NULL,
  GROUPNO VARCHAR(50) DEFAULT NULL,
  SDATE DATE DEFAULT NULL,
  EDATE DATE DEFAULT NULL,
  PRIMARY KEY (INSURANCEID)
);

CREATE TABLE HAS_INSURANCE (
  PID INT NOT NULL,
  INSURANCEID INT NOT NULL,
  PRIMARY KEY (PID, INSURANCEID),
  KEY INSURANCEID (INSURANCEID),
  FOREIGN KEY (PID) REFERENCES PATIENT(PID),
  FOREIGN KEY (INSURANCEID) REFERENCES INSURANCE_PROVIDER(INSURANCEID)
);


CREATE TABLE INITIAL_ASSESSMENT (
  ASSESSMENTID INT NOT NULL,
  VITALS VARCHAR(255) DEFAULT NULL,
  NURSEEMPLOYEEID INT DEFAULT NULL,
  VISITDATE DATE DEFAULT NULL,
  VISITTIME TIME DEFAULT NULL,
  PRIMARY KEY (ASSESSMENTID)
);


CREATE TABLE INTAKE_CLERK (
  EMPLOYEEID INT NOT NULL,
  SSN CHAR(9) NOT NULL,
  DEPARTMENTID INT DEFAULT NULL,
  FNAME VARCHAR(100) NOT NULL,
  MINITIAL CHAR(2) DEFAULT NULL,
  LNAME VARCHAR(100) NOT NULL,
  HOURLY INT DEFAULT NULL,
  SALARIED INT DEFAULT NULL,
  PRIMARY KEY (EMPLOYEEID),
  KEY DEPARTMENTID (DEPARTMENTID),
  FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE IT_SUPPORT (
  EMPLOYEEID INT NOT NULL,
  SSN CHAR(9) NOT NULL,
  DEPARTMENTID INT DEFAULT NULL,
  FNAME VARCHAR(100) NOT NULL,
  MINITIAL CHAR(2) DEFAULT NULL,
  LNAME VARCHAR(100) NOT NULL,
  HOURLY INT DEFAULT NULL,
  SALARIED INT DEFAULT NULL,
  PRIMARY KEY (EMPLOYEEID),
  KEY DEPARTMENTID (DEPARTMENTID),
  FOREIGN KEY (DEPARTMENTID) REFERENCES DEPARTMENT(DEPARTMENTID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE LOGS (
  DIAGNOSISID INT NOT NULL,
  EMPLOYEEID INT NOT NULL,
  PRIMARY KEY (DIAGNOSISID, EMPLOYEEID),
  KEY EMPLOYEEID (EMPLOYEEID),
  FOREIGN KEY (DIAGNOSISID) REFERENCES DIAGNOSIS(DIAGNOSISID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE MEDICATION (
  ASSESSMENTID INT NOT NULL,
  MEDICATIONNAME VARCHAR(255) NOT NULL,
  PRIMARY KEY (ASSESSMENTID, MEDICATIONNAME),
  FOREIGN KEY (ASSESSMENTID) REFERENCES INITIAL_ASSESSMENT(ASSESSMENTID)
);


CREATE TABLE NURSE_PRACTITIONER (
  EMPLOYEEID INT NOT NULL,
  PRIMARY KEY (EMPLOYEEID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);



CREATE TABLE PHYSICIAN_ASSISSTANT (
  EMPLOYEEID INT NOT NULL,
  PRIMARY KEY (EMPLOYEEID),
  FOREIGN KEY (EMPLOYEEID) REFERENCES EMPLOYEE(EMPLOYEEID)
);

CREATE TABLE SYMPTOMS (
  ASSESSMENTID INT NOT NULL,
  SYMPTOMDESCRIPTION VARCHAR(255) NOT NULL,
  PRIMARY KEY (ASSESSMENTID, SYMPTOMDESCRIPTION),
  FOREIGN KEY (ASSESSMENTID) REFERENCES INITIAL_ASSESSMENT(ASSESSMENTID)
);


