-- 1) Can a patient have different visits with the same diagnosis?
SELECT v.PID AS PatientID, d.DIAGNOSISID AS DiagnosisID, COUNT(DISTINCT v.VISITID) AS VisitCount
FROM VISIT v, LOGS l, DIAGNOSIS d
WHERE v.SERVICEPROVIDERID = l.EMPLOYEEID
AND l.DIAGNOSISID = d.DIAGNOSISID
GROUP BY v.PID, d.DIAGNOSISID
HAVING COUNT(v.VISITID) > 1;
