SELECT v.PID, t.TREATMENTNAME, COUNT(DISTINCT v.VISITID) AS VisitCount
FROM VISIT v
JOIN TREATMENT t ON v.VISITID = t.VISITID 
WHERE v.VISITID = t.VISITID
GROUP BY v.PID, t.TREATMENTNAME
HAVING COUNT(DISTINCT v.VISITID) > 1;